version: "2"

volumes:
  registry:

services:
  registry:
    image: registry:2
    restart: always
    ports:
      - 5000:5000
    volumes:
      - registry:/var/lib/registry
  gui:
    image: konradkleine/docker-registry-frontend:v2
    restart: always
    ports:
    - 8080:80
    environment:
    - ENV_DOCKER_REGISTRY_HOST=registry
    - ENV_DOCKER_REGISTRY_PORT=5000
