version: '2'

services:

  # Application python
  web:
    [ ... compléter ... ]
 
#    Option utiliser par le load balancer    
#    labels:
#      - "traefik.frontend.rule=Host:whoami.docker.localhost"
    depends_on:
    - redis

  redis:
  [ ... compléter ... ]

  # lb:
  #   image: traefik 
  #   command: --api --docker
  #   ports:
  #     - "80:80"     # The HTTP port
  #     - "8080:8080"   # GUI
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #   - app-network

networks:
  app-network:

volumes:
  redis-vol: